<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaymentSandbox.Domain\PaymentSandbox.Domain.csproj" />
    <ProjectReference Include="..\PaymentSandbox.Indexer\PaymentSandbox.Indexer.csproj" />
  </ItemGroup>
</Project>
