<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Nethereum.Signer.EIP712" />
    <PackageReference Include="Nethereum.Util" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaymentSandbox.Contracts\PaymentSandbox.Contracts.csproj" />
    <ProjectReference Include="..\PaymentSandbox.Domain\PaymentSandbox.Domain.csproj" />
  </ItemGroup>
</Project>
