// SPDX-License-Identifier: MIT
pragma solidity 0.8.36;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {IERC20Permit} from "@openzeppelin/contracts/token/ERC20/extensions/IERC20Permit.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";

/// @title PaymentRouter
/// @notice Moves ERC-20 tokens directly from a payer to a merchant and records
///         the payment facts in an event.
/// @dev This teaching contract is deliberately non-custodial and stateless. It
///      has no owner, upgrade mechanism, token allowlist, pause switch, or rescue
///      function. Production systems must enforce the accepted-token policy off
///      chain and reconcile this event against the token's Transfer event.
contract PaymentRouter {
    using SafeERC20 for IERC20;

    /// @notice A zero payment id cannot identify an off-chain payment intent.
    error InvalidPaymentId();

    /// @notice The token must be a deployed contract.
    error InvalidToken(address token);

    /// @notice A payment cannot target the zero address or this Router.
    error InvalidMerchant(address merchant);

    /// @notice ERC-20 amounts are atomic units and must be greater than zero.
    error InvalidAmount();

    /// @notice Emitted only after the token call reports a successful transfer.
    /// @dev paymentId uniqueness is intentionally not enforced on chain. Several
    ///      events may represent partial, repeated, or excess payments for the
    ///      same off-chain intent.
    /// @param paymentId Opaque identifier generated by the off-chain API.
    /// @param payer Account whose allowance and balance were used.
    /// @param token ERC-20 contract used for this transfer.
    /// @param merchant Direct recipient of the token transfer.
    /// @param amount Requested amount in the token's smallest unit.
    event PaymentRecorded(
        bytes32 indexed paymentId, address indexed payer, address token, address indexed merchant, uint256 amount
    );

    /// @notice Pays a merchant with allowance granted in an earlier transaction.
    /// @dev SafeERC20 accepts both standard boolean-returning tokens and legacy
    ///      tokens that return no value. It cannot make a malicious token safe,
    ///      so an emitted amount is not proof that a fee-on-transfer or dishonest
    ///      token delivered that amount. The indexer must verify Transfer logs.
    function pay(bytes32 paymentId, address token, address merchant, uint256 amount) external {
        _validatePayment(paymentId, token, merchant, amount);
        _transferAndRecord(paymentId, token, merchant, amount, msg.sender);
    }

    /// @notice Grants an exact ERC-2612 allowance and pays in one transaction.
    /// @dev The permit owner is always msg.sender, the spender is always this
    ///      Router, and the permit value is always the payment amount. Therefore
    ///      this teaching path intentionally does not support relayers. A permit
    ///      authorizes allowance only; it does not sign paymentId or merchant.
    ///      Because anyone can submit a public permit directly to the token, an
    ///      observer can consume its nonce before this call and make this strict
    ///      path fail closed. That is a known denial-of-service limitation; it
    ///      does not let the observer choose a merchant or paymentId for the owner.
    function payWithPermit(
        bytes32 paymentId,
        address token,
        address merchant,
        uint256 amount,
        uint256 permitDeadline,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external {
        // Validate first so an obviously invalid payment never reaches a token.
        // Any later revert still rolls back the permit nonce and allowance.
        _validatePayment(paymentId, token, merchant, amount);

        IERC20Permit(token).permit(msg.sender, address(this), amount, permitDeadline, v, r, s);
        _transferAndRecord(paymentId, token, merchant, amount, msg.sender);
    }

    function _validatePayment(bytes32 paymentId, address token, address merchant, uint256 amount) private view {
        if (paymentId == bytes32(0)) revert InvalidPaymentId();

        // SafeERC20 would eventually reject most EOAs, but checking code here
        // gives callers a stable, domain-specific error at the trust boundary.
        if (token == address(0) || token.code.length == 0) revert InvalidToken(token);

        // Paying the Router would turn an otherwise direct transfer into stuck
        // custody because this contract intentionally has no withdrawal method.
        if (merchant == address(0) || merchant == address(this)) revert InvalidMerchant(merchant);
        if (amount == 0) revert InvalidAmount();
    }

    function _transferAndRecord(bytes32 paymentId, address token, address merchant, uint256 amount, address payer)
        private
    {
        IERC20(token).safeTransferFrom(payer, merchant, amount);
        emit PaymentRecorded(paymentId, payer, token, merchant, amount);
    }
}
